/**
 * Generate src/version.ts from package.json so the version lives in exactly
 * one place. Run automatically before build/bundle/lint (see package.json
 * "pre*" scripts). CI additionally asserts the committed file is in sync.
 */
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
const target = resolve(root, 'src/version.ts');

const contents = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit.
// The single source of truth for the version is package.json.
export const VERSION = ${JSON.stringify(pkg.version)};
`;

let current = '';
try {
  current = readFileSync(target, 'utf8');
} catch {
  // file does not exist yet
}

if (current !== contents) {
  writeFileSync(target, contents);
  console.log(`✓ Wrote src/version.ts (v${pkg.version})`);
} else {
  console.log(`✓ src/version.ts already in sync (v${pkg.version})`);
}
