import fs from 'fs';
import path from 'path';
import chalk from 'chalk';
import { getConfig } from './config.js';
import { detectProjectContext } from './context.js';

const CASPER_DIR = '.casper';

const DEFAULT_CONFIG = `# Casper project configuration
# This file customizes how Casper behaves in this repository.

# Model override for this project (leave blank to use global config)
model: ""

# Custom system instructions appended to Casper's prompt
instructions: |
  # Add project-specific instructions here.
  # Example: "Always use pnpm instead of npm."
  # Example: "The test suite is run with: npm test"
  # Example: "This project uses PostgreSQL 15."

# Directories to exclude from context / search
ignore:
  - node_modules
  - .git
  - dist
  - build
  - coverage
  - __pycache__
  - .next

# Approval overrides for this project
# auto: run without asking
# confirm: ask before running
approval:
  destructive_commands: confirm
  file_writes: auto
  git_operations: auto
`;

const DEFAULT_INSTRUCTIONS = `# Custom Casper Instructions
# Lines in this file are appended to Casper's system prompt when
# working inside this project directory.
#
# Use this to give Casper persistent knowledge about your project:
# - Coding conventions
# - Architecture decisions
# - Testing patterns
# - Deployment procedures
#
# Example:
# This is a React + Express monorepo.
# Frontend is in src/, backend is in server.unified.ts.
# Always run "npm run lint" before committing.
# Tests use Vitest: "npm test"
`;

export async function initProject(opts: { force?: boolean } = {}): Promise<void> {
  const cwd = getConfig('workingDirectory') || process.cwd();
  const casperDir = path.join(cwd, CASPER_DIR);

  if (fs.existsSync(casperDir) && !opts.force) {
    console.log(chalk.yellow(`  ${CASPER_DIR}/ already exists in this directory.`));
    console.log(chalk.dim(`  Use --force to overwrite.`));
    return;
  }

  fs.mkdirSync(casperDir, { recursive: true });

  // Write config.yml
  fs.writeFileSync(path.join(casperDir, 'config.yml'), DEFAULT_CONFIG, 'utf-8');

  // Write instructions.md
  fs.writeFileSync(path.join(casperDir, 'instructions.md'), DEFAULT_INSTRUCTIONS, 'utf-8');

  // Auto-generate a context snapshot
  const ctx = detectProjectContext();
  if (ctx) {
    fs.writeFileSync(
      path.join(casperDir, 'context-snapshot.txt'),
      `# Auto-generated by casper init — ${new Date().toISOString()}\n# Re-generate with: casper init --force\n\n${ctx}\n`,
      'utf-8',
    );
  }

  // Add .casper to .gitignore if not already there
  const gitignorePath = path.join(cwd, '.gitignore');
  if (fs.existsSync(gitignorePath)) {
    const gitignore = fs.readFileSync(gitignorePath, 'utf-8');
    if (!gitignore.includes('.casper')) {
      console.log(chalk.dim(`  Note: .casper/ is NOT added to .gitignore.`));
      console.log(chalk.dim(`  Add it if you don't want to commit project instructions.`));
    }
  }

  console.log(chalk.magenta(`\n  🔮 Casper initialized in ${CASPER_DIR}/\n`));
  console.log(chalk.white(`  Created:`));
  console.log(chalk.dim(`    ${CASPER_DIR}/config.yml       — project settings`));
  console.log(chalk.dim(`    ${CASPER_DIR}/instructions.md  — custom AI instructions`));
  if (ctx) {
    console.log(chalk.dim(`    ${CASPER_DIR}/context-snapshot.txt — detected project info`));
  }
  console.log('');
  console.log(chalk.dim(`  Edit instructions.md to teach Casper about your project.`));
  console.log(chalk.dim(`  Casper will read these files automatically when you run commands here.`));
}

/**
 * Load project-level instructions from .casper/instructions.md if present.
 * Returns the instruction text or null.
 */
export function loadProjectInstructions(): string | null {
  const cwd = getConfig('workingDirectory') || process.cwd();
  const instrPath = path.join(cwd, CASPER_DIR, 'instructions.md');
  if (!fs.existsSync(instrPath)) return null;
  try {
    const raw = fs.readFileSync(instrPath, 'utf-8');
    // Strip comment lines starting with #
    const lines = raw.split('\n').filter(l => !l.startsWith('#')).join('\n').trim();
    return lines || null;
  } catch {
    return null;
  }
}

/**
 * Load project model override from .casper/config.yml if present.
 */
export function loadProjectModel(): string | null {
  const cwd = getConfig('workingDirectory') || process.cwd();
  const configPath = path.join(cwd, CASPER_DIR, 'config.yml');
  if (!fs.existsSync(configPath)) return null;
  try {
    const raw = fs.readFileSync(configPath, 'utf-8');
    const match = raw.match(/^model:\s*"?([^"\n]+)"?/m);
    const model = match?.[1]?.trim();
    return model || null;
  } catch {
    return null;
  }
}
